### ISSUE TITLE
Just a question:

### ISSUE THREAD

**Issue by fingermaster** [scotch-io/node-todo#10]
Is there something I am missing in setting up a DB on modulus? I created an account and seemingly went through all the steps... and this is my URL:
```
mongoose.connect('mongodb://<user>:<pwd>@apollo.modulusmongo.net:27017/esazO3hy');
```
But still get no response - yet connecting to yours does load fine.

Thanks for your help!

**Comment by sevilayha** [comment]
Just to be sure, did you change out the `<user>` and `<pwd>` parts of that url string?

**Comment by fingermaster** [comment]
Yes, it was an issue on Moduls' behalf... sorry to bother, I will close this.
