### ISSUE TITLE
js-bson : Module not found 

### ISSUE THREAD

**Issue by shivdhwaj** [scotch-io/node-todo#18]
![lol2](https://cloud.githubusercontent.com/assets/4490787/14008146/a35ebb8e-f1a3-11e5-9e38-1582f9da2136.png)

After clone running the application throws above mentioned thing.
OS: Ubuntu 14.04
NodeJs: v0.10.25 [Installed before the application cloning]

**Comment by Wuyue54** [comment]
Got the same problem too

**Comment by sevilayha** [comment]
Just had to update the dependencies in `package.json` to be the latest. Also make sure you're running the latest version of Node (v5.7.1 currently).
