### ISSUE TITLE
routes.js points to incorrect location for index.html

### ISSUE THREAD

**Issue by erip** [scotch-io/node-todo#20]
In the `routes.js` file, the app tries to load `index.html`, but it's looking in `__dirname + '/public/index.html'`.

`__dirname` is `proj_root/app/`, so `proj_root/app/public/index.html` is a 404. 

Because `server.js` sets the static file location, you should be able to use that.

**Comment by SashaDesigN** [comment]
Yes but I`m using this app and has no any errors

**Comment by sevilayha** [comment]
Yes also works for me as well. You could try replacing the `app.use(express.static...` line with the following:

```
app.use(express.static('./public'));
```

That will do directory root and will also work.
